'**INSERTS PAISES**'

INSERT INTO countries (name, alfaisotwo, alfaisothree, iscode) 
VALUES ('Afganistán', 'AF', 'AFG', '4'),
('Albania', 'AL', 'ALB', '8'),
('Alemania', 'DE', 'DEU', '276'),
('Andorra', 'AD', 'AND', '20'),
('Angola', 'AO', 'AGO', '24'),
('Anguilla', 'AI', 'AIA', '660'),
('Antártida', 'AQ', 'ATA', '10'),
('Antigua y Barbuda', 'AG', 'ATG', '28'),
('Arabia Saudí', 'SA', 'SAU', '682'),
('Argelia', 'DZ', 'DZA', '12'),
('Argentina', 'AR', 'ARG', '32'),
('Armenia', 'AM', 'ARM', '51'),
('Aruba', 'AW', 'ABW', '533'),
('Australia', 'AU', 'AUS', '36'),
('Austria', 'AT', 'AUT', '40'),
('Azerbaiyán', 'AZ', 'AZE', '31'),
('Bahamas', 'BS', 'BHS', '44'),
('Bangladés', 'BD', 'BGD', '50'),
('Barbados', 'BB', 'BRB', '52'),
('Baréin', 'BH', 'BHR', '48'),
('Belgica', 'BE', 'BEL', '56'),
('Belice', 'BZ', 'BLZ', '84'),
('Benin', 'BJ', 'BEN', '204'),
('Bermudas', 'BM', 'BMU', '60'),
('Bielorussia', 'BY', 'BLR', '112'),
('Birmania', 'MM', 'MMR', '104'),
('Bolivia', 'BO', 'BOL', '68'),
('Bosnia y Herzegovina', 'BA', 'BIH', '70'),
('Botsuana', 'BW', 'BWA', '72'),
('Brasil', 'BR', 'BRA', '76'),
('Brunéi', 'BN', 'BRN', '96'),
('Bulgaria', 'BG', 'BGR', '100'),
('Burkina Faso', 'BF', 'BFA', '854'),
('Burundi', 'BI', 'BDI', '108'),
('Bután', 'BT', 'BTN', '64'),
('Cabo Verde', 'CV', 'CPV', '132'),
('Camboya', 'KH', 'KHM', '116'),
('Camerún', 'CM', 'CMR', '120'),
('Canadá', 'CA', 'CAN', '124'),
('Caribe Neerlandés', 'BQ', 'BES', '535'),
('Catar', 'QA', 'QAT', '634'),
('Chad', 'TD', 'TCD', '148'),
('Chile', 'CL', 'CHL', '152'),
('China', 'CN', 'CHN', '156'),
('Chipre', 'CY', 'CYP', '196'),
('Colombia', 'CO', 'COL', '170'),
('Comoras', 'KM', 'COM', '174'),
('Corea del Norte', 'KP', 'PRK', '408'),
('Corea del Sur', 'KR', 'KOR', '410'),
('Costa de Marfil', 'CI', 'CIV', '384'),
('Costa Rica', 'CR', 'CRI', '188'),
('Croacia', 'HR', 'HRV', '191'),
('Cuba', 'CU', 'CUB', '192'),
('Curazao', 'CW', 'CUW', '531'),
('Dinamarca', 'DK', 'DNK', '208'),
('Dominica', 'DM', 'DMA', '212'),
('Ecuador', 'EC', 'ECU', '218'),
('Egipto', 'EG', 'EGY', '818'),
('El Salvador', 'SV', 'SLV', '222'),
('Emiratos árabes Unidos', 'AE', 'ARE', '784'),
('Eritrea', 'ER', 'ERI', '232'),
('Eslovaquia', 'SK', 'SVK', '703'),
('Eslovenia', 'SI', 'SVN', '705'),
('España', 'ES', 'ESP', '724'),
('Estados Federados de Micronesia', 'FM', 'FSM', '583'),
('Estados Unidos', 'US', 'USA', '840'),
('Estonia', 'EE', 'EST', '233'),
('Etiopía', 'ET', 'ETH', '231'),
('Filipinas', 'PH', 'PHL', '608'),
('Finlandia', 'FI', 'FIN', '246'),
('Fiyi', 'FJ', 'FJI', '242'),
('Francia', 'FR', 'FRA', '250'),
('Gabon', 'GA', 'GAB', '266'),
('Gambia', 'GM', 'GMB', '270'),
('Georgia', 'GE', 'GEO', '268'),
('Ghana', 'GH', 'GHA', '288'),
('Gibraltar', 'GI', 'GIB', '292'),
('Granada', 'GD', 'GRD', '308'),
('Grecia', 'GR', 'GRC', '300'),
('Groenlandia', 'GL', 'GRL', '304'),
('Guadelupe', 'GP', 'GLP', '312'),
('Guam', 'GU', 'GUM', '316'),
('Guatemala', 'GT', 'GTM', '320'),
('Guayana Francesa', 'GF', 'GUF', '254'),
('Guernsey', 'GG', 'GGY', '831'),
('Guinea', 'GN', 'GIN', '324'),
('Guinea Ecuatorial', 'GQ', 'GNQ', '226'),
('Guinea-Bissau', 'GW', 'GNB', '624'),
('Guyana', 'GY', 'GUY', '328'),
('Haití', 'HT', 'HTI', '332'),
('Honduras', 'HN', 'HND', '340'),
('Hong Kong', 'HK', 'HKG', '344'),
('Hungría', 'HU', 'HUN', '348'),
('Iceland', 'IS', 'ISL', '352'),
('India', 'IN', 'IND', '356'),
('Indonesia', 'ID', 'IDN', '360'),
('Irak', 'IQ', 'IRQ', '368'),
('Iran', 'IR', 'IRN', '364'),
('Isla de Man', 'IM', 'IMN', '833'),
('Isla de Navidad', 'CX', 'CXR', '162'),
('Isla Norfolk', 'NF', 'NFK', '574'),
('Islandia', 'IE', 'IRL', '372'),
('Islas Caimán', 'KY', 'CYM', '136'),
('Islas Cocos', 'CC', 'CCK', '166'),
('Islas Cook', 'CK', 'COK', '184'),
('Islas Feroe', 'FO', 'FRO', '234'),
('Islas Georgias y Sandwich del Sur', 'GS', 'SGS', '239'),
('Islas Malvinas', 'FK', 'FLK', '238'),
('Islas Marianas del Norte', 'MP', 'MNP', '580'),
('Islas Marshall', 'MH', 'MHL', '584'),
('Islas Pitcairn', 'PN', 'PCN', '612'),
('Islas Salomón', 'SB', 'SLB', '90'),
('Islas Turcas y Caicos', 'TC', 'TCA', '796'),
('Islas Vírgenes Británicas', 'VG', 'VGB', '92'),
('Islas Vírgenes de los Estados Unidos', 'VI', 'VIR', '850'),
('Israel', 'IL', 'ISR', '376'),
('Italia', 'IT', 'ITA', '380'),
('Jamaica', 'JM', 'JAM', '388'),
('Japón', 'JP', 'JPN', '392'),
('Jersey', 'JE', 'JEY', '832'),
('Jordania', 'JO', 'JOR', '400'),
('Kazajistán', 'KZ', 'KAZ', '398'),
('Kenia', 'KE', 'KEN', '404'),
('Kirguistán', 'KG', 'KGZ', '417'),
('Kiribati', 'KI', 'KIR', '296'),
('Kosovo', 'XK', 'XKX', '153'),
('Kuweit', 'KW', 'KWT', '414'),
('Laos', 'LA', 'LAO', '418'),
('Lesoto', 'LS', 'LSO', '426'),
('Letonia', 'LV', 'LVA', '428'),
('Libano', 'LB', 'LBN', '422'),
('Liberia', 'LR', 'LBR', '430'),
('Libia', 'LY', 'LBY', '434'),
('Liechtenstein', 'LI', 'LIE', '438'),
('Lituania', 'LT', 'LTU', '440'),
('Luxemburgo', 'LU', 'LUX', '442'),
('Macao', 'MO', 'MAC', '446'),
('Macedonia', 'MK', 'MKD', '807'),
('Madagascar', 'MG', 'MDG', '450'),
('Malasia', 'MY', 'MYS', '458'),
('Malaui', 'MW', 'MWI', '454'),
('Maldivas', 'MV', 'MDV', '462'),
('Mali', 'ML', 'MLI', '466'),
('Malta', 'MT', 'MLT', '470'),
('Marruecos', 'MA', 'MAR', '504'),
('Martinica', 'MQ', 'MTQ', '474'),
('Mauricio', 'MU', 'MUS', '480'),
('Mauritania', 'MR', 'MRT', '478'),
('Mayotte', 'YT', 'MYT', '175'),
('México', 'MX', 'MEX', '484'),
('Moldavia', 'MD', 'MDA', '498'),
('Monaco', 'MC', 'MCO', '492'),
('Mongolia', 'MN', 'MNG', '496'),
('Monténégro', 'ME', 'MNE', '499'),
('Montserrat', 'MS', 'MSR', '500'),
('Mozambique', 'MZ', 'MOZ', '508'),
('Namibia', 'NA', 'NAM', '516'),
('Nauru', 'NR', 'NRU', '520'),
('Nepal', 'NP', 'NPL', '524'),
('Nicaragua', 'NI', 'NIC', '558'),
('Niger', 'NE', 'NER', '562'),
('Nigeria', 'NG', 'NGA', '566'),
('Niue', 'NU', 'NIU', '570'),
('Noruega', 'NO', 'NOR', '578'),
('Nueva Caledonia', 'NC', 'NCL', '540'),
('Nueva Zelanda', 'NZ', 'NZL', '554'),
('Omán', 'OM', 'OMN', '512'),
('Países Bajos', 'NL', 'NLD', '528'),
('Pakistán', 'PK', 'PAK', '586'),
('Palaos', 'PW', 'PLW', '585'),
('Palestina', 'PS', 'PSE', '275'),
('Panama', 'PA', 'PAN', '591'),
('Papúa Nueva Guinea', 'PG', 'PNG', '598'),
('Paraguay', 'PY', 'PRY', '600'),
('Perú', 'PE', 'PER', '604'),
('Polinesia Francesa', 'PF', 'PYF', '258'),
('Polonia', 'PL', 'POL', '616'),
('Portugal', 'PT', 'PRT', '620'),
('Puerto Rico', 'PR', 'PRI', '630'),
('Reino Unido', 'GB', 'GBR', '826'),
('República árabe Saharaui DemocrÁtica', 'EH', 'ESH', '732'),
('República Centroafricana', 'CF', 'CAF', '140'),
('República Checa', 'CZ', 'CZE', '203'),
('República del Congo', 'CG', 'COG', '178'),
('República DemocrÁtica del Congo', 'CD', 'COD', '180'),
('República Dominicana', 'DO', 'DOM', '214'),
('Reunión', 'RE', 'REU', '638'),
('Ruanda', 'RW', 'RWA', '646'),
('Rumania', 'RO', 'ROU', '642'),
('Rusia', 'RU', 'RUS', '643'),
('Samoa', 'WS', 'WSM', '882'),
('Samoa Americana', 'AS', 'ASM', '16'),
('San Bartolomé', 'BL', 'BLM', '652'),
('San Cristóbal y Nieves', 'KN', 'KNA', '659'),
('San Marino', 'SM', 'SMR', '674'),
('San Martín', 'MF', 'MAF', '534'),
('San Pedro y Miquelón', 'PM', 'SPM', '666'),
('San Vicente y las Granadinas', 'VC', 'VCT', '670'),
('Santa Lucía', 'LC', 'LCA', '662'),
('Santo Tomé y Príncipe', 'ST', 'STP', '678'),
('Senegal', 'SN', 'SEN', '686'),
('Serbia', 'RS', 'SRB', '688'),
('Seychelles', 'SC', 'SYC', '690'),
('Sierra Leona', 'SL', 'SLE', '694'),
('Singapur', 'SG', 'SGP', '702'),
('Sint Helena, Ascension and Tristan da Cunha', 'SH', 'SHN', '654'),
('Sint-Maarten', 'SX', 'SXM', '663'),
('Siria', 'SY', 'SYR', '760'),
('Somalia', 'SO', 'SOM', '706'),
('Sri Lanka', 'LK', 'LKA', '144'),
('eSwatani', 'SZ', 'SWZ', '748'),
('Sudáfrica', 'ZA', 'ZAF', '710'),
('Sudán', 'SD', 'SDN', '729'),
('Sudán del Sur', 'SS', 'SSD', '728'),
('Suecia', 'SE', 'SWE', '752'),
('Suiza', 'CH', 'CHE', '756'),
('Surinam', 'SR', 'SUR', '740'),
('Tailandia', 'TH', 'THA', '764'),
('Taiwan', 'TW', 'TWN', '158'),
('Tanzania', 'TZ', 'TZA', '834'),
('Tayikistán', 'TJ', 'TJK', '762'),
('Territorio Británico del Océano índico', 'IO', 'IOT', '86'),
('Tierras Australes y Antárticas Francesas', 'TF', 'ATF', '260'),
('Timor Oriental', 'TL', 'TLS', '626'),
('Togo', 'TG', 'TGO', '768'),
('Tokelau', 'TK', 'TKL', '772'),
('Tonga', 'TO', 'TON', '776'),
('Trinidad y Tobago', 'TT', 'TTO', '780'),
('Túnez', 'TN', 'TUN', '788'),
('Turkmenistán', 'TM', 'TKM', '795'),
('Turquía', 'TR', 'TUR', '792'),
('Tuvalu', 'TV', 'TUV', '798'),
('Ucrania', 'UA', 'UKR', '804'),
('Uganda', 'UG', 'UGA', '800'),
('Uruguay', 'UY', 'URY', '858'),
('Uzbekistán', 'UZ', 'UZB', '860'),
('Vanuatu', 'VU', 'VUT', '548'),
('Vaticano', 'VA', 'VAT', '336'),
('Venezuela', 'VE', 'VEN', '862'),
('Vietnam', 'VN', 'VNM', '704'),
('Wallis y Futuna', 'WF', 'WLF', '876'),
('Yemen', 'YE', 'YEM', '887'),
('Yibuti', 'DJ', 'DJI', '262'),
('Zambia', 'ZM', 'ZMB', '894'),
('Zimbabwe', 'ZW', 'ZWE', '716');

'INSERT SUBDIVICIONES**'

INSERT INTO subdivisioncategories (description) 
VALUES ('departament'),('capital district'),('state'),('district'),('outlying area');

**INSERT Regiones y estados**


INSERT INTO stateorregions(code,nombre,country_id,code3166,subdivision_id)
VALUES ()